"use client";
import { CreatorShell, CreatorWorkspace, CreatorSettingsPanel, CreatorCanvas, CreatorPrimaryAction } from "@/app/components/creator/creator-shell";
import Link from 'next/link';
import { Skeleton, EmptyState } from "@/app/components/ui/workspace";
import {useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {Button} from '@/app/components/ui/button';
import {TextField} from '@/app/components/ui/text-field';
import {StatusMessage} from '@/app/components/ui/status-message';
import {DEFAULT_BRIEF,GOALS,MODES,REVIEW_LABELS,exportPlan,type Brief,type PlannerState,type SavedPlan} from '@/lib/ads/model';
import type {Library} from '@/lib/media/model';
import {MetaExportPanel} from './meta-export-panel';
const field='mt-2 w-full rounded-xl border border-white/15 bg-[#101018] p-3 text-white';
const card='min-w-0 rounded-3xl border border-white/10 bg-white/[0.03] p-5 sm:p-7';
const money=(n:number)=>n.toLocaleString('th-TH',{maximumFractionDigits:2});
async function result(r:Response){const data=await r.json();if(!r.ok)throw new Error(data.error||'ดำเนินการไม่สำเร็จ');return data;}
export default function AdsPage(){
  const [state,setState]=useState<PlannerState|null>(null),[library,setLibrary]=useState<Library|null>(null),[brief,setBrief]=useState<Brief>(DEFAULT_BRIEF),[selected,setSelected]=useState<string|null>(null);
  const [busy,setBusy]=useState(false),[login,setLogin]=useState(false),[checked,setChecked]=useState(false),[message,setMessage]=useState(''),[asOf,setAsOf]=useState(0);
  const gate=useRef(false),request=useRef<{key:string;id:string}|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const responses=await Promise.all([fetch('/api/ads-plans',{cache:'no-store',signal}),fetch('/api/assets',{cache:'no-store',signal})]);if(responses.some(r=>r.status===401)){setLogin(true);return;}const [s,l]=await Promise.all(responses.map(result));setState(s);setLibrary(l);setAsOf(Date.now());},[]);
  useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>{void refresh(c.signal).catch(e=>{if(!c.signal.aborted)setMessage(e.message);});},0);return()=>{clearTimeout(timer);c.abort();};},[refresh]);
  const pending=state?.plans.some(p=>p.analysis_state==='running');
  useEffect(()=>{if(!pending)return;const c=new AbortController();const timer=setInterval(()=>{if(!document.hidden)void refresh(c.signal).catch(()=>{});},5000);return()=>{clearInterval(timer);c.abort();};},[pending,refresh]);
  const plan=state?.plans.find(p=>p.id===selected)||null;
  function update<K extends keyof Brief>(key:K,value:Brief[K]){setBrief(b=>({...b,[key]:value}));}
  async function act(fn:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'ดำเนินการไม่สำเร็จ');}finally{gate.current=false;setBusy(false);}}
  async function submit(e:FormEvent){e.preventDefault();await act(async()=>{const key=JSON.stringify(brief);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};const data=await result(await fetch('/api/ads-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:request.current.id,brief})}));await refresh();setSelected(data.id);setChecked(false);});}
  function download(p:SavedPlan){const url=URL.createObjectURL(new Blob([exportPlan(p)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`ads-plan-${p.id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <CreatorShell title="แผนโฆษณา" description="เปลี่ยนรายละเอียดโปรโมชันและงบประมาณเป็นแผนพร้อมใช้">
    
    {message&&<StatusMessage tone="error" className="mb-5">{message}</StatusMessage>}
    {login?<Link href="/sign-in" className="text-purple-200 underline">เข้าสู่ระบบเพื่อวางแผน</Link>:!state?<div className={card}>{message ? <p>เปิดแผนไม่สำเร็จ กรุณาลองอีกครั้ง</p> : <Skeleton label="กำลังโหลดแผน" />}<Button className="mt-4" onClick={()=>void act(()=>refresh())}>โหลดใหม่</Button></div>:<>
      <CreatorWorkspace><CreatorSettingsPanel>
        <form onSubmit={submit}><h2 className="mb-5 text-xl font-bold">รายละเอียดโปรโมชัน</h2><fieldset disabled={busy} className="space-y-4">
          <TextField label="ชื่อแผน" required maxLength={100} value={brief.title} onChange={e=>update('title',e.target.value)} placeholder="โปรโมชั่น ROV สัปดาห์นี้"/>
          <TextField label="เกม" required maxLength={80} value={brief.game} onChange={e=>update('game',e.target.value)} placeholder="เช่น ROV"/>
          <label className="block text-sm">ข้อความโพสต์<textarea className={field} required maxLength={4000} rows={5} value={brief.caption} onChange={e=>update('caption',e.target.value)} placeholder="วางข้อความโปรโมชั่น รวมแพ็ก ราคา และเงื่อนไขจริง"/></label>
          <TextField label="ลิงก์ Facebook (ไม่บังคับ)" type="url" maxLength={1000} value={brief.postUrl} onChange={e=>update('postUrl',e.target.value)} placeholder="https://www.facebook.com/…"/>
          <p className="text-xs leading-6 text-muted">เก็บลิงก์ไว้อ้างอิง กรุณาวางข้อความโพสต์ด้านบน ระบบยังไม่ดึงข้อมูลจาก Facebook</p>
          <label className="block text-sm">สื่อจากคลัง<select className={field} value={brief.assetId||''} onChange={e=>update('assetId',e.target.value||null)}><option value="">ยังไม่เลือกสื่อ</option>{library?.assets.filter(a=>a.state==='ready'&&new Date(a.expires_at).getTime()>asOf).map(a=><option value={a.id} key={a.id}>{a.name} ({a.kind==='image'?'ภาพ':'วิดีโอ'})</option>)}</select></label>
          <Link href="/dashboard/library" className="block text-xs text-purple-200 underline">เพิ่มภาพหรือคลิปในคลัง</Link>
          <h2 className="pt-5 text-xl font-bold">เป้าหมายและงบ</h2>
          <label className="block text-sm">อยากได้อะไรจากโฆษณา<select className={field} value={brief.goal} onChange={e=>setBrief(b=>({...b,goal:e.target.value as Brief['goal'],costLow:null,costHigh:null}))}>{Object.entries(GOALS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
          <label className="block text-sm">แนวทางใช้เงิน<select className={field} value={brief.mode} onChange={e=>update('mode',e.target.value as Brief['mode'])}>{Object.entries(MODES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
          <div className="grid grid-cols-2 gap-3"><TextField label="งบรวม (บาท)" type="number" required min={1} max={1000000} step="0.01" value={brief.budget} onChange={e=>update('budget',Number(e.target.value))}/><TextField label="จำนวนวัน" type="number" required min={1} max={90} step={1} value={brief.days} onChange={e=>update('days',Number(e.target.value))}/></div>
          <p className="text-sm text-purple-200">เฉลี่ย {Number.isFinite(brief.budget/brief.days)?money(brief.budget/brief.days):'—'} บาท / วัน</p>
          <details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer text-sm font-bold">เพิ่มข้อมูลให้แผนแม่นขึ้น (ไม่บังคับ)</summary><div className="mt-4 space-y-4">
            <TextField label="ประเทศที่ขาย" required maxLength={80} value={brief.country} onChange={e=>update('country',e.target.value)}/>
            <TextField label="กลุ่มลูกค้าที่คุณรู้จัก" maxLength={300} value={brief.audience} onChange={e=>update('audience',e.target.value)}/>
            <Check checked={brief.warmAudience} onChange={v=>update('warmAudience',v)}>มีกลุ่มคนที่เคยสนใจพร้อมใช้ในบัญชีโฆษณาแล้ว</Check>
            {brief.goal==='sales'&&<Check checked={brief.trackingReady} onChange={v=>update('trackingReady',v)}>มีเว็บไซต์และทดสอบการวัดรายการซื้อแล้ว</Check>}
            <TextField label="กำไรต่อรายการก่อนหักค่าแอด (บาท)" type="number" min="0.01" max={1000000} step="0.01" value={brief.profit??''} onChange={e=>update('profit',e.target.value===''?null:Number(e.target.value))}/>
            <p className="text-sm leading-6 text-white/65">ต้นทุน{brief.goal==='awareness'?'ต่อการแสดง 1,000 ครั้ง':brief.goal==='messages'?'ต่อการสนทนา':brief.goal==='visits'?'ต่อคลิก':'ต่อรายการซื้อ'}ที่เคยพบ หรือสมมติฐานที่ต้องการลอง</p>
            <div className="grid grid-cols-2 gap-3"><TextField label="ค่าต่ำ (บาท)" type="number" min="0.01" max={1000000} step="0.01" value={brief.costLow??''} onChange={e=>update('costLow',e.target.value===''?null:Number(e.target.value))}/><TextField label="ค่าสูง (บาท)" type="number" min="0.01" max={1000000} step="0.01" value={brief.costHigh??''} onChange={e=>update('costHigh',e.target.value===''?null:Number(e.target.value))}/></div><p className="text-xs text-muted">ไม่ทราบให้เว้นว่าง ระบบจะไม่เดาจำนวนลูกค้าให้</p>
          </div></details>
          <Check disabled={!state.aiAvailable} checked={brief.ai} onChange={v=>update('ai',v)}>ให้ AI ตรวจข้อความและภาพที่เลือก (ส่งข้อมูลนี้ให้ผู้ให้บริการ AI)</Check>
          <p className="text-xs leading-6 text-muted">{state.aiAvailable?'AI ตรวจภาพนิ่งและข้อความ ไม่วิเคราะห์เนื้อหาภายในวิดีโอ และไม่รับรองความจริงของข้อเสนอ':'AI ยังไม่เปิดใช้งาน ใช้การคำนวณงบและรายการตรวจได้ก่อน'}</p>
          <CreatorPrimaryAction quota={state.entitlement.enabled ? `เหลือ ${Math.max(0,state.entitlement.limit-state.entitlement.used)} แผนเดือนนี้` : "บัญชีนี้ยังไม่ได้เปิดสิทธิ์วางแผน"}><Button type="submit" fullWidth disabled={busy||!state.entitlement.enabled||state.entitlement.used>=state.entitlement.limit} loading={busy}>สร้างและบันทึกแผน</Button><p className="text-xs leading-6 text-muted">ใช้สิทธิ์ 1 แผน ไม่หักโควตาภาพหรือวิดีโอ แก้ข้อมูลแล้วสร้างใหม่จะบันทึกเป็นอีกแผน</p></CreatorPrimaryAction>
        </fieldset></form></CreatorSettingsPanel>
        <CreatorCanvas title="แผนโฆษณาของคุณ"><h2 className="text-xl font-bold">แผนของคุณ</h2>{!plan?<div className="py-16 text-center"><p className="text-3xl">◎</p><p className="mt-5 text-white/65">สร้างแผนแรก หรือเปิดแผนที่บันทึกไว้</p><p className="mt-2 text-sm text-muted">งบ · แนวทาง · สิ่งที่ต้องปรับ · วิธีดูผล</p></div>:<div className="mt-6 space-y-6">
          <div><p className="text-xs text-purple-300">{plan.accepted_at?'ตรวจแผนแล้ว · ยังไม่ได้ยิงโฆษณา':'รอตรวจแผน'}</p><h3 className="mt-2 break-words text-2xl font-bold">{plan.brief.title}</h3><p className="mt-2 text-xs text-muted">ข้อมูลร้านเวอร์ชัน {plan.brand_version} · {plan.brand.shopName||'ยังไม่ตั้งชื่อร้าน'}</p></div>
          <div className="grid grid-cols-3 gap-2"><Metric label="งบรวม" value={`${money(plan.brief.budget)} ฿`}/><Metric label="ระยะเวลา" value={`${plan.brief.days} วัน`}/><Metric label="เฉลี่ย / วัน" value={`${money(plan.result.dailyAverage)} ฿`}/></div>
          <Block title="เป้าหมายที่แนะนำ"><p>{plan.result.objective}</p><p className="mt-2 text-muted">{plan.result.strategy}</p></Block>
          <Block title="เงินแบ่งไปที่ไหน">{plan.result.allocation.map(a=><div key={a.label} className="flex justify-between gap-3 py-2"><span>{a.label}</span><strong className="shrink-0">{money(a.amount)} ฿</strong></div>)}<p className="mt-2 text-muted">{plan.result.allocationReason}</p></Block>
          <Block title="ประมาณการจากสมมติฐาน">{plan.result.estimates?<><p className="text-2xl font-bold text-purple-200">{money(plan.result.estimates.low)}–{money(plan.result.estimates.high)} {plan.result.unit}</p><p className="mt-3">ใช้ต้นทุนที่คุณกรอก {money(plan.result.estimates.lowCost)}–{money(plan.result.estimates.highCost)} บาท{plan.brief.goal==='awareness'?' ต่อ 1,000 ครั้ง':' ต่อผลลัพธ์'}</p><p className="mt-2 text-amber-200">เป็นสถานการณ์จำลอง ไม่ใช่การรับประกันผลจริง{plan.brief.goal==='awareness'?' และไม่ใช่จำนวนคนที่เข้าถึง':''}</p></>:<p className="text-muted">ยังไม่มีต้นทุนอ้างอิง จึงยังไม่ประมาณจำนวนผลลัพธ์ เพิ่มข้อมูลจากการยิงครั้งก่อนเพื่อจำลองได้</p>}{plan.result.breakEven!==null&&<p className="mt-3">ต้องขายอย่างน้อย <strong>{money(plan.result.breakEven)} รายการ</strong> เพื่อชดเชยค่าแอดตามกำไรที่กรอก (ไม่ใช่ยอดขายที่คาดว่าจะได้)</p>}</Block>
          <Block title="ตรวจโพสต์และสื่อ"><p className="mb-3 text-xs text-muted">{plan.analysis_state==='ai'?'AI ตรวจเบื้องต้น · โปรดตรวจต้นฉบับอีกครั้ง':plan.analysis_state==='running'?'AI กำลังตรวจ เปิดกลับมาดูได้':'ยังไม่มีผลตรวจจาก AI · ใช้รายการตรวจด้วยตนเอง'}{plan.analysis_state==='fallback'?' เพราะการวิเคราะห์ไม่สำเร็จ':''}</p>{plan.review&&Object.entries(REVIEW_LABELS).map(([k,label])=><p key={k}>{label}: <strong>{({yes:'พบ',no:'ควรปรับ',unclear:'ยังสรุปไม่ได้'})[plan.review![k as keyof typeof REVIEW_LABELS]]}</strong></p>)}<p className="mt-3 text-muted">{plan.asset_name?`สื่อ: ${plan.asset_name}${plan.asset_available?'':' (ถูกลบหรือหมดอายุแล้ว)'}`:'ยังไม่เลือกสื่อ'}</p><ul className="mt-3 list-disc space-y-2 pl-5">{plan.result.checklist.map(s=><li key={s}>{s}</li>)}</ul></Block>
          <Block title="กลุ่มลูกค้าและสื่อ"><p>{plan.result.audience}</p><p className="mt-3 text-muted">{plan.result.placement}</p><p className="mt-3 text-muted">{plan.result.experiment}</p></Block>
          <Block title="ดูอะไรหลังเริ่มโฆษณา"><p>{plan.result.kpi}</p></Block>
          <details><summary className="cursor-pointer text-sm text-purple-200">ข้อความต้นฉบับและงบแต่ละวัน</summary><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-7">{plan.result.copy}</p><p className="mt-3 text-sm">คำชวนจากร้าน: {plan.result.cta}</p><div className="mt-4 max-h-48 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>วันที่</th><th>งบ (บาท)</th></tr></thead><tbody>{plan.result.dailySchedule.map(d=><tr key={d.day}><td>{d.day}</td><td>{money(d.amount)}</td></tr>)}</tbody></table></div></details>
          <ul className="space-y-2 rounded-2xl bg-amber-300/5 p-4 text-xs leading-6 text-amber-100/80">{plan.result.warnings.map(w=><li key={w}>{w}</li>)}</ul>
          {!plan.accepted_at&&<><Check checked={checked} onChange={setChecked}>ตรวจข้อมูลและสมมติฐานแล้ว รับทราบว่ายังไม่ใช่การยิงโฆษณา</Check><Button disabled={!checked||busy||plan.analysis_state==='running'} onClick={()=>void act(async()=>{await result(await fetch(`/api/ads-plans/${plan.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true})}));await refresh();setChecked(false);})}>ยืนยันว่าตรวจแผนแล้ว</Button></>}
          <div className="flex flex-wrap gap-3"><Button variant="secondary" onClick={()=>download(plan)}>ดาวน์โหลดแผนข้อความ</Button><Button variant="secondary" disabled={busy} onClick={()=>{setBrief({...plan.brief,ai:false,assetId:plan.asset_available?plan.brief.assetId:null});request.current=null;setSelected(null);setChecked(false);window.scrollTo({top:0,behavior:'smooth'});}}>ใช้ข้อมูลนี้สร้างแผนใหม่</Button></div>
          <MetaExportPanel key={plan.id} plan={plan}/>
        </div>}</CreatorCanvas>
      </CreatorWorkspace>
      <section className="studio-recent"><div className="mb-4 flex items-center justify-between gap-4"><h2 className="text-xl font-bold">แผนที่บันทึกไว้</h2><button className="text-sm text-purple-200 underline" disabled={busy} onClick={()=>void act(()=>refresh())}>รีเฟรช</button></div><div className="ads-recent-list">{state.plans.map(p=><button key={p.id} disabled={busy} onClick={()=>{setSelected(p.id);setChecked(false);}} className={`${card} text-left transition hover:border-purple-300/60 ${p.id===selected?'border-purple-300/60':''}`}><p className="break-words font-bold">{p.brief.title}</p><p className="mt-2 text-sm text-muted">{money(p.brief.budget)} บาท · {p.brief.days} วัน</p><p className="mt-2 text-xs text-purple-200">{p.accepted_at?'ตรวจแล้ว':p.analysis_state==='running'?'AI กำลังตรวจ':'รอตรวจแผน'}</p></button>)}</div>{!state.plans.length&&<EmptyState title="ยังไม่มีแผนโฆษณา" description="เริ่มจากรายละเอียดโปรโมชันและงบประมาณด้านบน" action="เริ่มกรอกแผน" onAction={() => document.querySelector<HTMLInputElement>('input')?.focus()} />}</section>
    </>}
  </CreatorShell>;
}
function Check({checked,onChange,disabled,children}:{checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean;children:ReactNode}){return <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1.5" type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{children}</span></label>;}
function Block({title,children}:{title:string;children:ReactNode}){return <section className="border-t border-white/10 pt-5 text-sm leading-7"><h4 className="mb-3 font-bold text-white">{title}</h4>{children}</section>;}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-purple-400/10 p-3"><p className="text-xs text-muted">{label}</p><p className="mt-2 break-words font-bold text-purple-100">{value}</p></div>;}
