"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { ReactNode } from "react";
import { Button } from "@/app/components/ui/button";
const features = [["/", "✦", "ภาพโปรโม"], ["/dashboard/motion", "▷", "วิดีโอจากภาพ"], ["/dashboard/frame", "▣", "กรอบวิดีโอ"], ["/dashboard/ads", "↗", "แผนโฆษณา"]];
export function CreatorFeatureTabs() { const pathname = usePathname(); return <nav className="creator-feature-tabs" aria-label="เครื่องมือสร้างงาน">{features.map(([href, icon, label]) => <Link key={href} href={href} aria-current={pathname === href ? "page" : undefined}><span aria-hidden="true">{icon}</span>{label}</Link>)}</nav>; }
export function CreatorShell({ title, description, action, children }: { title: string; description: string; action?: ReactNode; children: ReactNode }) { return <main className="creator-shell"><header className="creator-heading"><div className="creator-heading-copy"><span className="creator-eyebrow"><span aria-hidden="true">✦</span> LAZY-AI.GAME STUDIO</span><h1>{title}</h1><p>{description}</p></div>{action && <div className="creator-heading-action">{action}</div>}</header><CreatorFeatureTabs />{children}</main>; }
export function CreatorWorkspace({ children }: { children: ReactNode }) { return <div className="creator-workspace">{children}</div>; }
export function CreatorSettingsPanel({ children }: { children: ReactNode }) { return <section aria-label="ตั้งค่าชิ้นงาน" className="creator-settings"><div className="creator-panel-heading"><span className="creator-panel-step" aria-hidden="true">01</span><div><strong>ตั้งค่าชิ้นงาน</strong><p>เลือกข้อมูลและรูปแบบที่ต้องการ</p></div></div>{children}</section>; }
export function CreatorCanvas({ children, busy = false, title = "พื้นที่สร้างสรรค์" }: { children: ReactNode; busy?: boolean; title?: string }) { return <section className="creator-canvas" aria-label={title} aria-busy={busy}><div className="canvas-label"><span className="creator-panel-step" aria-hidden="true">02</span><div><strong>{title}</strong><p>ตัวอย่างและผลลัพธ์ของงาน</p></div><span className="creator-canvas-status">{busy ? "กำลังสร้าง" : "พร้อมสร้าง"}</span></div>{children}</section>; }
export function CreatorPrimaryAction({ children, quota }: { children: ReactNode; quota?: ReactNode }) { return <div className="creator-primary-action">{quota && <p className="creator-quota">{quota}</p>}{children}</div>; }
export function CreatorGenerationState({ title, description, processing = false }: { title: string; description?: string; processing?: boolean }) { return <div className="creator-generation-state" role={processing ? "status" : undefined}><span className={processing ? "canvas-processing" : ""} aria-hidden="true">{processing ? "◌" : "✦"}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
export function CreatorResultActions({ downloadHref, onNewVersion }: { downloadHref?: string; onNewVersion: () => void }) { return <div className="creator-result-actions">{downloadHref && <a className="action-link" href={downloadHref} download>ดาวน์โหลด MP4</a>}<Button variant="secondary" onClick={onNewVersion}>สร้างอีกเวอร์ชัน</Button><Link href="/dashboard/library" className="action-link secondary">เปิดในคลัง</Link></div>; }
