"use client";
import Link from 'next/link';
import Image from 'next/image';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Button } from '@/app/components/ui/button';
import { TextField } from '@/app/components/ui/text-field';
import { StatusMessage } from '@/app/components/ui/status-message';
import type { Asset,Library } from '@/lib/media/model';
import { DEFAULT_PLAN,fitPoster,MOTION_LABELS,parsePlan,type MotionJob,type MotionPlan,type Studio } from '@/lib/motion/model';
async function result(response:Response) {const data=await response.json();if(!response.ok)throw new Error(data.error||'ดำเนินการไม่สำเร็จ');return data;}
export default function MotionPage() {
  const [studio,setStudio]=useState<Studio|null>(null),[library,setLibrary]=useState<Library|null>(null);
  const [selected,setSelected]=useState(''),[title,setTitle]=useState(''),[jobId,setJobId]=useState('');
  const [reviewed,setReviewed]=useState('');
  const [plan,setPlan]=useState<MotionPlan>(DEFAULT_PLAN),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [feedback,setFeedback]=useState<{tone:'error'|'success';message:string}|null>(null);
  const [asOf,setAsOf]=useState(0),[needsLogin,setNeedsLogin]=useState(false);
  const gate=useRef(false),auth=useRef(false),draftKey=useRef<{payload:string;id:string}|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{
    const responses=await Promise.all([fetch('/api/motion',{cache:'no-store',signal}),fetch('/api/assets',{cache:'no-store',signal})]);
    if(responses.some(r=>r.status===401)){auth.current=true;setNeedsLogin(true);return;}
    const [next,assets]=await Promise.all(responses.map(result));setStudio(next);setLibrary(assets);setAsOf(Date.now());
  },[]);
  useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{if(!document.hidden)await refresh(controller.signal);}catch(error){if(!controller.signal.aborted)setFeedback({tone:'error',message:error instanceof Error?error.message:'โหลดข้อมูลไม่ได้'});}finally{if(!controller.signal.aborted&&!auth.current)timer=setTimeout(poll,5000);}};
    void poll();return()=>{controller.abort();clearTimeout(timer);};
  },[refresh]);
  const job=studio?.jobs.find(j=>j.id===jobId);
  const source=library?.assets.find(a=>a.id===(job?.source_asset_id||selected));
  const images=library?.assets.filter(a=>a.kind==='image'&&a.state==='ready'&&new Date(a.expires_at).getTime()>asOf)||[];
  async function act(work:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setFeedback(null);try{await work();await refresh();}catch(error){setFeedback({tone:'error',message:error instanceof Error?error.message:'ดำเนินการไม่สำเร็จ'});}finally{gate.current=false;setBusy(false);}}
  function edit(next:MotionPlan){setPlan(next);setConfirmed(false);}
  function review(next:MotionJob){setReviewed(next.id+':'+next.revision);setJobId(next.id);setSelected(next.source_asset_id);setPlan(next.plan);setConfirmed(false);setFeedback(null);}
  return <main className="min-h-screen bg-[#08080e] px-5 py-9 text-white sm:px-8"><div className="mx-auto max-w-6xl">
    <nav aria-label="เส้นทางหน้า" className="mb-9 flex flex-wrap gap-3 text-sm text-white/55"><Link href="/dashboard">บัญชีของฉัน</Link><span>/</span><Link href="/dashboard/library">คลังงาน</Link><span>/</span><span className="text-purple-200">สร้างวิดีโอ</span></nav>
    <header className="mb-8"><p className="mb-3 text-xs font-bold tracking-widest text-purple-300">LAZY-AI.GAME / MOTION STUDIO</p><h1 className="text-3xl font-black sm:text-4xl">เปลี่ยนภาพโปรโมชั่นให้ขยับได้</h1><p className="mt-3 text-sm leading-7 text-white/55">เลือกภาพ → ตรวจแผนเคลื่อนไหว → รับวิดีโอ MP4</p></header>
    {feedback&&<StatusMessage tone={feedback.tone} className="mb-5">{feedback.message}</StatusMessage>}
    {needsLogin?<Link href="/sign-in" className="text-purple-200 underline">เข้าสู่ระบบเพื่อสร้างวิดีโอ</Link>:!studio||!library?<p role="status">กำลังโหลดสตูดิโอ...</p>:<>
      <div className="mb-6 rounded-2xl border border-white/10 bg-white/[0.025] p-5"><p className="font-bold">โควตาวิดีโอเดือนนี้</p><p className="mt-2 text-sm text-white/60">ใช้แล้ว {studio.entitlement.used} / {studio.entitlement.limit} คลิป · กำลังจอง {studio.entitlement.reserved} คลิป</p><p className="mt-2 text-xs leading-6 text-white/45">สร้างสำเร็จใช้ 1 คลิป · แยกจากโควตาภาพ · เริ่มรอบใหม่วันที่ 1 ตามเวลา UTC</p>{!studio.entitlement.enabled&&<p className="mt-3 text-sm text-amber-200">บัญชีนี้ยังไม่ได้เปิดสิทธิ์วิดีโอช่วงทดลองใช้งาน</p>}</div>
      <div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]">
        <section className="min-w-0 rounded-3xl border border-white/10 p-6"><h2 className="mb-5 text-xl font-bold">1. เลือกภาพโปรโมชั่น</h2>
          <label className="block text-sm text-white/70">ภาพจากคลัง<select disabled={busy||Boolean(job)} value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full min-w-0 rounded-xl border border-white/15 bg-[#15151d] p-3"><option value="">เลือกภาพที่พร้อมใช้</option>{images.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
          <Link href="/dashboard/library" className="mt-3 inline-block text-xs text-purple-200 underline">อัปโหลดภาพหรือเลือกภาพในชุดงานที่คลัง</Link>
          {!job&&<form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void act(async()=>{const payload=JSON.stringify({sourceAssetId:selected,title});if(draftKey.current?.payload!==payload)draftKey.current={payload,id:crypto.randomUUID()};const next=await result(await fetch('/api/motion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draftKey.current.id,sourceAssetId:selected,title})}));setJobId(next.id);});}}><TextField label="ชื่อวิดีโอ" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100} disabled={busy}/><Button type="submit" disabled={busy||!selected||!studio.entitlement.enabled}>{busy?'กำลังส่ง...':'วิเคราะห์ภาพและเตรียมแผน'}</Button><p className="text-xs leading-6 text-white/45">ยังไม่ใช้โควตาสร้างวิดีโอในขั้นตอนนี้</p></form>}
          {job&&<div className="mt-5"><p role="status" className="text-purple-200">{MOTION_LABELS[job.state]}</p>{job.state==='review'&&<Button className="mt-3" variant="secondary" onClick={()=>review(job)}>เปิดแผนที่เตรียมไว้</Button>}<button type="button" disabled={busy} onClick={()=>{setJobId('');setSelected('');setTitle('');setPlan(DEFAULT_PLAN);setConfirmed(false);draftKey.current=null;}} className="ml-4 mt-3 text-sm text-white/60 underline">สร้างงานใหม่</button></div>}
          {source&&<div className="mt-6"><MotionPreview asset={source} plan={plan}/><p className="mt-3 text-xs leading-6 text-white/45">ตัวอย่างการเคลื่อนไหวโดยประมาณ · ภาพอยู่ครบในกรอบ · MP4 ไม่มีเสียง</p></div>}
        </section>
        <section className="min-w-0 rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">2. ตรวจแผนก่อนสร้าง</h2>
          {!job||job.state!=='review'||reviewed!==job.id+':'+job.revision?<p className="mt-4 text-sm leading-7 text-white/50">{job?.state==='analyzing'?'กำลังเตรียมแผน คุณปิดหน้านี้แล้วกลับมาดูต่อได้':'เลือกงานที่พร้อมตรวจแผนจากรายการด้านล่าง เพื่อแก้ไขและสร้างวิดีโอ'}</p>:<>
            <p className="mt-3 text-sm leading-7 text-white/55">{job.analysis_source==='vision'?'AI เสนอตำแหน่งให้แล้ว กรุณาตรวจว่ากรอบไม่ทับข้อความสำคัญ':'ยังไม่ได้ใช้ผลวิเคราะห์ AI คุณเพิ่มกรอบไฮไลต์เอง หรือใช้ภาพเคลื่อนไหวทั้งภาพได้'}</p>
            <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">ความยาว<select value={plan.duration} onChange={e=>edit({...plan,duration:Number(e.target.value) as MotionPlan['duration']})} className="mt-2 w-full rounded-xl bg-[#15151d] p-3">{[6,10,15].map(v=><option key={v} value={v}>{v} วินาที</option>)}</select></label><label className="text-sm">สัดส่วน<select value={plan.ratio} onChange={e=>edit({...plan,ratio:e.target.value as MotionPlan['ratio']})} className="mt-2 w-full rounded-xl bg-[#15151d] p-3"><option>9:16</option><option>1:1</option><option>16:9</option></select></label></div>
            <label className="mt-4 block text-sm">การเคลื่อนไหว<select value={plan.effect} onChange={e=>edit({...plan,effect:e.target.value as MotionPlan['effect']})} className="mt-2 w-full rounded-xl bg-[#15151d] p-3"><option value="float">ภาพลอยเบา ๆ</option><option value="still">ภาพนิ่ง + ไฮไลต์ตามลำดับ</option></select></label>
            <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">กรอบไฮไลต์ {plan.boxes.length}/6</h3><button type="button" disabled={plan.boxes.length>=6||busy} onClick={()=>edit({...plan,boxes:[...plan.boxes,{x:10,y:60,width:80,height:20,kind:'price'}]})} className="rounded-lg border border-purple-300/40 px-3 py-2 text-xs text-purple-200 disabled:opacity-40">＋ เพิ่มกรอบ</button></div>
            <p className="mt-2 text-xs leading-6 text-white/45">ตำแหน่งเป็นเปอร์เซ็นต์จากซ้ายและบนของภาพ กรอบจะแสดงเรียงทีละตำแหน่ง โดยไม่เขียนราคาใหม่</p>
            {plan.boxes.map((box,index)=><fieldset key={index} disabled={busy} className="mt-4 rounded-xl border border-white/10 p-4"><legend className="px-2 text-xs text-purple-200">กรอบ {index+1}</legend><div className="mb-3 flex justify-between gap-3"><select aria-label={`ประเภทกรอบ ${index+1}`} value={box.kind} onChange={e=>edit({...plan,boxes:plan.boxes.map((b,i)=>i===index?{...b,kind:e.target.value as typeof box.kind}:b)})} className="min-w-0 rounded-lg bg-[#15151d] p-2 text-xs"><option value="price">แพ็กเกจ / ราคา</option><option value="visual">ตัวละคร / ภาพหลัก</option></select><button type="button" onClick={()=>edit({...plan,boxes:plan.boxes.filter((_,i)=>i!==index)})} className="text-xs text-white/55 underline">ลบกรอบ</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{([['x','ซ้าย'],['y','บน'],['width','กว้าง'],['height','สูง']] as const).map(([key,label])=><label key={key} className="text-xs text-white/65">{label} %<input type="number" min={0} max={100} step={1} value={box[key]} onChange={e=>edit({...plan,boxes:plan.boxes.map((b,i)=>i===index?{...b,[key]:Number(e.target.value)}:b)})} className="mt-1 w-full rounded-lg bg-[#15151d] p-2"/></label>)}</div></fieldset>)}
            <label className="mt-6 flex items-start gap-3 text-sm leading-6 text-white/75"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 accent-purple-400"/>ตรวจภาพ ราคา และกรอบไฮไลต์แล้ว ยืนยันสร้างวิดีโอโดยใช้โควตา 1 คลิป</label>
            <Button className="mt-4 w-full" disabled={busy||!confirmed||!studio.entitlement.enabled||!studio.storageAvailable} onClick={()=>void act(async()=>{parsePlan(plan);await result(await fetch(`/api/motion/${job.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:job.revision,plan,confirmed:true})}));setFeedback({tone:'success',message:'รับงานแล้ว ปิดหน้าเว็บและกลับมาดาวน์โหลดภายหลังได้'});})}>{busy?'กำลังส่งงาน...':'ยืนยันและสร้าง MP4'}</Button>
            {!studio.storageAvailable&&<p className="mt-3 text-sm text-amber-200">พื้นที่เก็บวิดีโอยังไม่พร้อมใช้งาน</p>}<p className="mt-3 text-xs leading-6 text-white/45">จองพื้นที่สูงสุด 32 MB และคืนส่วนต่างหลังสร้างสำเร็จ หากล้มเหลวจะคืนโควตาหลังเก็บกวาดไฟล์</p>
          </>}
        </section>
      </div>
      <section className="mt-9"><h2 className="mb-5 text-xl font-bold">งานวิดีโอของฉัน</h2>{studio.jobs.length===0?<p className="text-sm text-white/50">ยังไม่มีงานวิดีโอ เริ่มจากเลือกภาพด้านบน</p>:<div className="grid gap-4 sm:grid-cols-2">{studio.jobs.map(item=><article key={item.id} className="min-w-0 rounded-2xl border border-white/10 p-5"><h3 className="break-words font-bold">{item.title}</h3><p className="mt-2 text-sm text-purple-200">{MOTION_LABELS[item.state]}</p><p className="mt-2 text-xs text-white/45">{item.plan.duration} วินาที · {item.plan.ratio} · แบรนด์เวอร์ชัน {item.brand_version}</p>{item.state==='retry'&&<p className="mt-2 text-xs leading-6 text-amber-200">กำลังเก็บกวาดไฟล์ก่อนลองใหม่ อาจใช้เวลาประมาณ 1 ชั่วโมงต่อรอบ</p>}<div className="mt-4 flex flex-wrap items-center gap-4">{item.state==='review'&&<Button variant="secondary" disabled={busy} onClick={()=>review(item)}>ตรวจและแก้แผน</Button>}{item.state==='succeeded'&&(item.output_ready?<a href={`/api/assets/${item.output_asset_id}`} className="text-sm text-purple-200 underline">ดาวน์โหลด MP4</a>:<span className="text-xs text-white/50">ไฟล์ถูกลบหรือหมดอายุแล้ว</span>)}{['analyzing','review','queued','retry'].includes(item.state)&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm('ยกเลิกงานวิดีโอนี้?'))void act(async()=>{await result(await fetch(`/api/motion/${item.id}`,{method:'DELETE'}));});}} className="text-xs text-white/50 underline">ยกเลิกงาน</button>}</div></article>)}</div>}</section>
    </>}
  </div></main>;
}
function MotionPreview({asset,plan}:{asset:Asset;plan:MotionPlan}) {
  const [natural,setNatural]=useState<{width:number;height:number}|null>(null);
  const [playing,setPlaying]=useState(false),[elapsed,setElapsed]=useState(0);
  useEffect(()=>{if(!playing)return;let raf=0;const start=performance.now();const tick=(now:number)=>{setElapsed(((now-start)/1000)%plan.duration);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,plan.duration]);
  const frame=fitPoster(natural?.width||asset.metadata?.width||1,natural?.height||asset.metadata?.height||1,plan.ratio);
  const y=playing&&plan.effect==='float'?6*Math.sin(2*Math.PI*elapsed/plan.duration):0;
  return <><div className="relative mx-auto w-full max-w-80 overflow-hidden rounded-xl border border-white/15 bg-[#08080e]" style={{aspectRatio:`${frame.width}/${frame.height}`}}><div className="absolute" style={{width:`${frame.posterWidth/frame.width*100}%`,height:`${frame.posterHeight/frame.height*100}%`,left:`${(frame.width-frame.posterWidth)/2/frame.width*100}%`,top:`${((frame.height-frame.posterHeight)/2+y)/frame.height*100}%`}}><Image onLoad={e=>setNatural({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} unoptimized fill sizes="320px" src={`/api/assets/${asset.id}/preview`} alt={`ภาพต้นฉบับ ${asset.name}`} className="object-contain"/>{plan.boxes.map((box,i)=><span key={i} className="pointer-events-none absolute border-2" style={{left:`${box.x}%`,top:`${box.y}%`,width:`${box.width}%`,height:`${box.height}%`,borderColor:box.kind==='price'?'#fde047':'#c4b5fd',opacity:!playing||Math.floor(elapsed/plan.duration*plan.boxes.length)===i?1:0}}>{!playing&&<span className="absolute -top-4 left-0 bg-black/80 px-1 text-[10px] text-white">{i+1}</span>}</span>)}</div></div><button type="button" onClick={()=>setPlaying(v=>!v)} className="mt-3 w-full rounded-xl border border-white/15 py-2 text-sm text-purple-200">{playing?'หยุดตัวอย่าง':'เล่นตัวอย่างแผน'}</button></>;
}
