"use client";
import Link from 'next/link';
import Image from 'next/image';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/app/components/ui/button';
import {TextField} from '@/app/components/ui/text-field';
import {StatusMessage} from '@/app/components/ui/status-message';
import {CONTACT_LABELS,type BrandProfile} from '@/lib/brand/model';
import type {Library} from '@/lib/media/model';
import {MOTION_LABELS,type MotionJob,type Studio} from '@/lib/motion/model';
import {DEFAULT_FRAME,FRAME,parseFrame,type FramePlan} from '@/lib/frame/model';
type FrameJob=MotionJob&{clip_asset_id:string;frame_plan:FramePlan};
type FrameStudio=Omit<Studio,'jobs'>&{jobs:FrameJob[]};
type Detail={id:string;brand:BrandProfile;brandVersion:number;frame:FramePlan;revision:number;state:string;sourceAssetId:string;clipAssetId:string};
async function result(response:Response){const data=await response.json();if(!response.ok)throw new Error(data.error||'ดำเนินการไม่สำเร็จ');return data;}
export default function FramePage(){
  const [studio,setStudio]=useState<FrameStudio|null>(null),[library,setLibrary]=useState<Library|null>(null),[detail,setDetail]=useState<Detail|null>(null);
  const [source,setSource]=useState(''),[clip,setClip]=useState(''),[title,setTitle]=useState(''),[plan,setPlan]=useState<FramePlan>(DEFAULT_FRAME);
  const [preview,setPreview]=useState(''),[previewKey,setPreviewKey]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[login,setLogin]=useState(false),[asOf,setAsOf]=useState(0);
  const [feedback,setFeedback]=useState<{tone:'error'|'success';message:string}|null>(null);
  const gate=useRef(false),auth=useRef(false),url=useRef(''),video=useRef<HTMLVideoElement>(null),key=useRef<{payload:string;id:string}|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const responses=await Promise.all([fetch('/api/frame',{cache:'no-store',signal}),fetch('/api/assets',{cache:'no-store',signal})]);if(responses.some(r=>r.status===401)){auth.current=true;setLogin(true);return;}const [next,assets]=await Promise.all(responses.map(result));setStudio(next);setLibrary(assets);setAsOf(Date.now());},[]);
  useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(!document.hidden)await refresh(controller.signal);}catch(error){if(!controller.signal.aborted)setFeedback({tone:'error',message:error instanceof Error?error.message:'โหลดไม่ได้'});}finally{if(!controller.signal.aborted&&!auth.current)timer=setTimeout(poll,5000);}};void poll();return()=>{controller.abort();clearTimeout(timer);if(url.current)URL.revokeObjectURL(url.current);};},[refresh]);
  async function act(work:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setFeedback(null);try{await work();await refresh();}catch(error){setFeedback({tone:'error',message:error instanceof Error?error.message:'ดำเนินการไม่สำเร็จ'});}finally{gate.current=false;setBusy(false);}}
  function edit(next:FramePlan){setPlan(next);setConfirmed(false);}
  async function open(jobId:string){const data=await result(await fetch(`/api/frame/${jobId}`,{cache:'no-store'})) as Detail;setDetail(data);setPlan(data.frame);setSource(data.sourceAssetId);setClip(data.clipAssetId);setConfirmed(false);setPreview('');setPreviewKey('');}
  const images=library?.assets.filter(a=>a.kind==='image'&&a.state==='ready'&&new Date(a.expires_at).getTime()>asOf)||[];
  const clips=library?.assets.filter(a=>a.kind==='video'&&a.state==='ready'&&new Date(a.expires_at).getTime()>asOf&&(a.metadata?.duration||0)>=6)||[];
  const selectedClip=library?.assets.find(a=>a.id===clip);
  const current=studio?.jobs.find(j=>j.id===detail?.id);
  const editable=detail&&current?.state==='review';
  const previewCurrent=Boolean(detail&&preview&&previewKey===JSON.stringify({id:detail.id,plan}));
  const selectClass='mt-2 w-full min-w-0 rounded-xl border border-white/15 bg-[#15151d] p-3';
  return <main className="min-h-screen bg-[#08080e] px-5 py-9 text-white sm:px-8"><div className="mx-auto max-w-6xl">
    <nav className="mb-9 flex flex-wrap gap-3 text-sm text-white/55" aria-label="เส้นทางหน้า"><Link href="/dashboard">บัญชีของฉัน</Link><span>/</span><Link href="/dashboard/library">คลังงาน</Link><span>/</span><span className="text-purple-200">จัดกรอบวิดีโอ</span></nav>
    <header className="mb-8"><p className="mb-3 text-xs font-bold tracking-widest text-purple-300">LAZY-AI.GAME / VIDEO FRAME</p><h1 className="text-3xl font-black sm:text-4xl">คลิปของคุณ พร้อมกรอบโปรโมชั่น</h1><p className="mt-3 text-sm leading-7 text-white/55">ภาพโปรโมชั่นด้านบน · คลิปตรงกลาง · ข้อมูลร้านและช่องทางสั่งซื้อด้านล่าง</p></header>
    {feedback&&<StatusMessage tone={feedback.tone} className="mb-5">{feedback.message}</StatusMessage>}
    {login?<Link href="/sign-in" className="text-purple-200 underline">เข้าสู่ระบบเพื่อจัดกรอบวิดีโอ</Link>:!studio||!library?<p role="status">กำลังโหลดข้อมูล...</p>:<>
      <div className="mb-6 rounded-2xl border border-white/10 p-5"><p className="font-bold">โควตาวิดีโอร่วมกับ Motion Studio</p><p className="mt-2 text-sm text-white/60">ใช้แล้ว {studio.entitlement.used}/{studio.entitlement.limit} คลิป · จองไว้ {studio.entitlement.reserved} คลิป</p>{!studio.entitlement.enabled&&<p className="mt-3 text-sm text-amber-200">บัญชีนี้ยังไม่ได้เปิดสิทธิ์วิดีโอช่วงทดลอง</p>}</div>
      <div className="grid gap-6 lg:grid-cols-2"><section className="min-w-0 rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">1. เลือกภาพและคลิป</h2>
        <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void act(async()=>{const payload=JSON.stringify({sourceAssetId:source,clipAssetId:clip,title});if(key.current?.payload!==payload)key.current={payload,id:crypto.randomUUID()};const created=await result(await fetch('/api/frame',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(payload),id:key.current.id})}));await open(created.id);});}}>
          <label className="block text-sm">ภาพโปรโมชั่น<select className={selectClass} value={source} disabled={busy||Boolean(detail)} onChange={e=>setSource(e.target.value)} required><option value="">เลือกภาพจากคลัง</option>{images.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
          <label className="block text-sm">คลิปเกมหรือคลิปสินค้า<select className={selectClass} value={clip} disabled={busy||Boolean(detail)} onChange={e=>setClip(e.target.value)} required><option value="">เลือกคลิปอย่างน้อย 6 วินาที</option>{clips.map(a=><option key={a.id} value={a.id}>{a.name} · {a.metadata?.duration?.toFixed(1)} วินาที</option>)}</select></label>
          <Link href="/dashboard/library" className="inline-block text-xs text-purple-200 underline">เพิ่มไฟล์ที่คลังงาน</Link>
          {!detail?<><TextField label="ชื่อวิดีโอ" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100}/><Button type="submit" disabled={busy||!source||!clip||!studio.entitlement.enabled}>เตรียมกรอบจากข้อมูลร้าน</Button><p className="text-xs text-white/45">ขั้นตอนนี้ยังไม่ใช้โควตาวิดีโอ</p></>:<button type="button" disabled={busy} onClick={()=>{setDetail(null);setSource('');setClip('');setTitle('');setPreview('');setPreviewKey('');setConfirmed(false);key.current=null;}} className="mt-3 block text-sm text-purple-200 underline">สร้างงานใหม่</button>}
        </form>
        {detail&&<><p className="mt-5 text-sm text-purple-200">Brand Kit เวอร์ชัน {detail.brandVersion} · {MOTION_LABELS[current?.state||detail.state]}</p><Link href="/dashboard/brand" className="mt-2 inline-block text-xs text-white/55 underline">แก้ข้อมูลร้านสำหรับงานใหม่</Link></>}
        {preview&&<div className="mt-6"><div className="relative mx-auto aspect-[9/16] w-full max-w-80 overflow-hidden rounded-xl border border-white/10 bg-black"><video ref={video} src={`/api/assets/${clip}?inline=1`} controls playsInline muted={!plan.audio} preload="metadata" onLoadedMetadata={e=>{e.currentTarget.currentTime=plan.start;}} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=plan.start+plan.duration){e.currentTarget.pause();e.currentTarget.currentTime=plan.start;}}} style={{position:'absolute',left:`${FRAME.clipX/720*100}%`,top:`${FRAME.clipY/1280*100}%`,width:`${FRAME.clipWidth/720*100}%`,height:`${FRAME.clipHeight/1280*100}%`,objectFit:plan.fit}}/><Image unoptimized fill src={preview} alt="ตัวอย่างกรอบโปรโมชั่นและข้อมูลร้าน" className="pointer-events-none"/></div><p className={`mt-3 text-xs leading-6 ${previewCurrent?'text-white/45':'text-amber-200'}`}>{previewCurrent?'กรอบนี้ใช้ภาพเดียวกับที่จะส่งออก MP4 · ปุ่มเล่นไม่ปรากฏในไฟล์จริง':'มีการแก้ไข กรุณาอัปเดตตัวอย่างก่อนยืนยัน'}</p></div>}
      </section>
      <section className="min-w-0 rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-bold">2. ปรับกรอบและตรวจตัวอย่าง</h2>{!editable?<p className="mt-4 text-sm leading-7 text-white/50">เลือกภาพกับคลิปและเตรียมกรอบก่อน หรือเปิดงานรอตรวจจากรายการด้านล่าง</p>:<div className="mt-5 space-y-4">
        <TextField label="ข้อความหัวโปรโมชั่น (ไม่จำเป็น)" value={plan.headline} maxLength={60} onChange={e=>edit({...plan,headline:e.target.value})}/>
        <TextField label="ข้อความชวนสั่งซื้อ (ไม่จำเป็น)" value={plan.cta} maxLength={60} onChange={e=>edit({...plan,cta:e.target.value})}/>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">เริ่มคลิปที่วินาที<input className={selectClass} type="number" min={0} max={Math.max(0,(selectedClip?.metadata?.duration||0)-plan.duration)} step={0.1} value={plan.start} onChange={e=>edit({...plan,start:Number(e.target.value)})}/></label><label className="text-sm">ความยาว<select className={selectClass} value={plan.duration} onChange={e=>edit({...plan,duration:Number(e.target.value) as FramePlan['duration']})}>{[6,10,15].map(v=><option key={v} value={v}>{v} วินาที</option>)}</select></label></div>
        <label className="block text-sm">จัดคลิปในช่อง<select className={selectClass} value={plan.fit} onChange={e=>edit({...plan,fit:e.target.value as FramePlan['fit']})}><option value="contain">เห็นคลิปครบทั้งภาพ</option><option value="cover">เต็มช่อง (ครอบขอบภาพ)</option></select></label>
        <label className="flex gap-3 text-sm"><input type="checkbox" checked={plan.audio} onChange={e=>edit({...plan,audio:e.target.checked})}/>ใช้เสียงต้นฉบับ ถ้าคลิปมีเสียง</label>
        <label className="flex gap-3 text-sm"><input type="checkbox" checked={plan.logo&&Boolean(detail.brand.logoId)} disabled={!detail.brand.logoId} onChange={e=>edit({...plan,logo:e.target.checked})}/>แสดงโลโก้ร้าน{!detail.brand.logoId?' (ยังไม่มีโลโก้)':''}</label>
        <label className="block text-sm">ช่องทางสั่งซื้อ<select className={selectClass} value={plan.contact} onChange={e=>edit({...plan,contact:e.target.value as FramePlan['contact']})}><option value="">ไม่แสดง</option>{(Object.keys(CONTACT_LABELS) as (keyof typeof CONTACT_LABELS)[]).filter(k=>detail.brand.contacts[k]).map(k=><option key={k} value={k}>{CONTACT_LABELS[k]}</option>)}</select></label>
        <label className="flex gap-3 text-sm"><input type="checkbox" disabled={!detail.brand.paymentMethods.length} checked={plan.payments} onChange={e=>edit({...plan,payments:e.target.checked})}/>แสดงช่องทางชำระเงินที่ร้านตั้งไว้</label>
        <label className="block text-sm">ข้อความที่ร้านยืนยัน<select className={selectClass} value={plan.trustIndex??''} onChange={e=>edit({...plan,trustIndex:e.target.value===''?null:Number(e.target.value)})}><option value="">ไม่แสดง</option>{detail.brand.claimsConfirmed&&detail.brand.trustStatements.map((text,i)=><option key={i} value={i}>{text}</option>)}</select></label>
        <Button variant="secondary" disabled={busy} onClick={()=>void act(async()=>{parseFrame(plan);if(plan.start+plan.duration>(selectedClip?.metadata?.duration||0)+0.001)throw new Error('ช่วงเวลาที่เลือกยาวเกินคลิปต้นฉบับ');const response=await fetch(`/api/frame/${detail.id}/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(plan)});if(!response.ok){await result(response);return;}const blob=await response.blob();if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);setPreview(url.current);setPreviewKey(JSON.stringify({id:detail.id,plan}));setConfirmed(false);if(video.current)video.current.currentTime=plan.start;})}>{preview?'อัปเดตตัวอย่างกรอบ':'สร้างตัวอย่างกรอบ'}</Button>
        <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" checked={confirmed} disabled={!previewCurrent} onChange={e=>setConfirmed(e.target.checked)}/>ตรวจภาพ ข้อความ ข้อมูลร้าน และช่วงคลิปแล้ว ยืนยันใช้โควตา 1 คลิป</label>
        <Button className="w-full" disabled={busy||!confirmed||!previewCurrent||!studio.entitlement.enabled||!studio.storageAvailable} onClick={()=>void act(async()=>{await result(await fetch(`/api/frame/${detail.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:detail.revision,frame:plan,confirmed:true})}));setFeedback({tone:'success',message:'รับงานแล้ว กลับมาดาวน์โหลดวิดีโอได้เมื่อสร้างสำเร็จ'});})}>ยืนยันและสร้าง MP4</Button><p className="text-xs leading-6 text-white/45">แนวตั้ง 720 × 1280 · จองพื้นที่สูงสุด 32 MB · ภาพโปรโมชั่นและราคาไม่ถูกเขียนใหม่</p>
      </div>}</section></div>
      <section className="mt-9"><h2 className="mb-5 text-xl font-bold">งานจัดกรอบของฉัน</h2>{!studio.jobs.length?<p className="text-sm text-white/50">ยังไม่มีงานจัดกรอบวิดีโอ</p>:<div className="grid gap-4 sm:grid-cols-2">{studio.jobs.map(job=><article key={job.id} className="min-w-0 rounded-2xl border border-white/10 p-5"><h3 className="break-words font-bold">{job.title}</h3><p className="mt-2 text-sm text-purple-200">{MOTION_LABELS[job.state]}</p><p className="mt-2 text-xs text-white/45">{job.frame_plan.duration} วินาที · Brand Kit เวอร์ชัน {job.brand_version}</p>{job.state==='retry'&&<p className="mt-2 text-xs text-amber-200">เก็บกวาดไฟล์ก่อนลองใหม่ อาจใช้เวลาประมาณ 1 ชั่วโมงต่อรอบ</p>}<div className="mt-4 flex flex-wrap gap-4">{job.state==='review'&&<Button variant="secondary" disabled={busy} onClick={()=>void act(()=>open(job.id))}>เปิดกรอบและแก้ไข</Button>}{job.state==='succeeded'&&(job.output_ready?<a href={`/api/assets/${job.output_asset_id}`} className="text-sm text-purple-200 underline">ดาวน์โหลด MP4</a>:<span className="text-xs text-white/50">ไฟล์ถูกลบหรือหมดอายุแล้ว</span>)}{['review','queued','retry'].includes(job.state)&&<button disabled={busy} onClick={()=>{if(window.confirm('ยกเลิกงานนี้?'))void act(async()=>{await result(await fetch(`/api/frame/${job.id}`,{method:'DELETE'}));});}} className="text-xs text-white/50 underline">ยกเลิกงาน</button>}</div></article>)}</div>}</section>
    </>}
  </div></main>;
}
