"use client";
import { AssetPicker } from '@/app/components/creator/asset-picker';
import { CreatorShell, CreatorWorkspace, CreatorSettingsPanel, CreatorCanvas, CreatorPrimaryAction, CreatorGenerationState, CreatorResultActions } from '@/app/components/creator/creator-shell';
import Link from 'next/link';
import { Skeleton, EmptyState } from "@/app/components/ui/workspace";
import Image from 'next/image';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/app/components/ui/button';
import {TextField} from '@/app/components/ui/text-field';
import {StatusMessage} from '@/app/components/ui/status-message';
import {CONTACT_LABELS,type BrandProfile} from '@/lib/brand/model';
import type {Library} from '@/lib/media/model';
import {MOTION_LABELS,type MotionJob,type Studio} from '@/lib/motion/model';
import {DEFAULT_FRAME,FRAME,parseFrame,type FramePlan} from '@/lib/frame/model';
type FrameJob=MotionJob&{clip_asset_id:string;frame_plan:FramePlan};
type FrameStudio=Omit<Studio,'jobs'>&{jobs:FrameJob[]};
type Detail={id:string;brand:BrandProfile;brandVersion:number;frame:FramePlan;revision:number;state:string;sourceAssetId:string;clipAssetId:string};
async function result(response:Response){const data=await response.json();if(!response.ok)throw new Error(data.error||'ดำเนินการไม่สำเร็จ');return data;}
export default function FramePage(){
  const [studio,setStudio]=useState<FrameStudio|null>(null),[library,setLibrary]=useState<Library|null>(null),[detail,setDetail]=useState<Detail|null>(null);
  const [source,setSource]=useState(''),[clip,setClip]=useState(''),[title,setTitle]=useState(''),[plan,setPlan]=useState<FramePlan>(DEFAULT_FRAME);
  const [preview,setPreview]=useState(''),[previewKey,setPreviewKey]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[login,setLogin]=useState(false),[asOf,setAsOf]=useState(0);
  const [feedback,setFeedback]=useState<{tone:'error'|'success';message:string}|null>(null);
  const gate=useRef(false),auth=useRef(false),url=useRef(''),video=useRef<HTMLVideoElement>(null),key=useRef<{payload:string;id:string}|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const responses=await Promise.all([fetch('/api/frame',{cache:'no-store',signal}),fetch('/api/assets',{cache:'no-store',signal})]);if(responses.some(r=>r.status===401)){auth.current=true;setLogin(true);return;}const [next,assets]=await Promise.all(responses.map(result));setStudio(next);setLibrary(assets);setAsOf(Date.now());},[]);
  useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(!document.hidden)await refresh(controller.signal);}catch(error){if(!controller.signal.aborted)setFeedback({tone:'error',message:error instanceof Error?error.message:'โหลดไม่ได้'});}finally{if(!controller.signal.aborted&&!auth.current)timer=setTimeout(poll,5000);}};void poll();return()=>{controller.abort();clearTimeout(timer);if(url.current)URL.revokeObjectURL(url.current);};},[refresh]);
  async function act(work:()=>Promise<void>){if(gate.current)return;gate.current=true;setBusy(true);setFeedback(null);try{await work();await refresh();}catch(error){setFeedback({tone:'error',message:error instanceof Error?error.message:'ดำเนินการไม่สำเร็จ'});}finally{gate.current=false;setBusy(false);}}
  function edit(next:FramePlan){setPlan(next);setConfirmed(false);}
  async function renderPreview(id:string,frame:FramePlan,clipId=clip){parseFrame(frame);if(frame.start+frame.duration>(library?.assets.find(a=>a.id===clipId)?.metadata?.duration||0)+0.001)throw new Error('ช่วงเวลาที่เลือกยาวเกินคลิปต้นฉบับ');const response=await fetch(`/api/frame/${id}/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(frame)});if(!response.ok){await result(response);return;}const blob=await response.blob();if(url.current)URL.revokeObjectURL(url.current);url.current=URL.createObjectURL(blob);setPreview(url.current);setPreviewKey(JSON.stringify({id,plan:frame}));setConfirmed(false);if(video.current)video.current.currentTime=frame.start;}
  async function open(jobId:string){const data=await result(await fetch(`/api/frame/${jobId}`,{cache:'no-store'})) as Detail;setDetail(data);setPlan(data.frame);setSource(data.sourceAssetId);setClip(data.clipAssetId);setConfirmed(false);setPreview('');setPreviewKey('');if(data.state==='review')await renderPreview(data.id,data.frame,data.clipAssetId);}
  const selectedClip=library?.assets.find(a=>a.id===clip);
  const current=studio?.jobs.find(j=>j.id===detail?.id);
  const editable=detail&&current?.state==='review';
  const previewCurrent=Boolean(detail&&preview&&previewKey===JSON.stringify({id:detail.id,plan}));
  const selectClass='mt-2 w-full min-w-0 rounded-xl border border-white/15 bg-[#15151d] p-3';
  return <CreatorShell title="จัดกรอบวิดีโอ" description="รวมภาพโปรโมชัน คลิป และข้อมูลร้าน พร้อมตรวจตัวอย่างก่อนส่งออก">

    {feedback&&<StatusMessage tone={feedback.tone} className="mb-5">{feedback.message}</StatusMessage>}
    {login?<Link href="/sign-in" className="text-purple-200 underline">เข้าสู่ระบบเพื่อจัดกรอบวิดีโอ</Link>:!studio||!library?<div>{feedback ? <EmptyState title="เปิดสตูดิโอไม่สำเร็จ" description="ลองโหลดอีกครั้งเพื่อทำงานต่อ" action="ลองอีกครั้ง" onAction={() => void act(() => refresh())} /> : <Skeleton />}</div>:<>
      <CreatorWorkspace><CreatorSettingsPanel><h2 className="studio-section-title">ภาพและคลิปต้นฉบับ</h2>
        <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();void act(async()=>{const payload=JSON.stringify({sourceAssetId:source,clipAssetId:clip,title:title.trim()||"วิดีโอโปรโมชัน"});if(key.current?.payload!==payload)key.current={payload,id:crypto.randomUUID()};const created=await result(await fetch('/api/frame',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...JSON.parse(payload),id:key.current.id})}));await open(created.id);});}}>
          <AssetPicker library={library} asOf={asOf} value={source} onChange={setSource} onUploaded={refresh} disabled={busy||Boolean(detail)}/>
          <AssetPicker kind="video" library={library} asOf={asOf} value={clip} onChange={setClip} onUploaded={refresh} disabled={busy||Boolean(detail)}/>
          {!detail?<><TextField label="ชื่อวิดีโอ" value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/><CreatorPrimaryAction quota={`เหลือ ${Math.max(0,studio.entitlement.limit-studio.entitlement.used-studio.entitlement.reserved)} คลิปเดือนนี้`}><Button type="submit" fullWidth disabled={busy||library.assets.find(a=>a.id===source)?.state!=="ready"||library.assets.find(a=>a.id===clip)?.state!=="ready"||!studio.entitlement.enabled}>เตรียมกรอบจากข้อมูลร้าน</Button><p className="text-xs text-muted">ขั้นตอนนี้ยังไม่ใช้โควตาวิดีโอ</p></CreatorPrimaryAction></>:<button type="button" disabled={busy} onClick={()=>{setDetail(null);setPreview('');setPreviewKey('');setConfirmed(false);key.current=null;}} className="mt-3 block text-sm text-purple-200 underline">สร้างงานใหม่</button>}
        </form>
        {detail&&<><p className="mt-5 text-sm text-purple-200">Brand Kit เวอร์ชัน {detail.brandVersion} · {MOTION_LABELS[current?.state||detail.state]}</p><Link href="/dashboard/brand" className="mt-2 inline-block text-xs text-muted underline">แก้ข้อมูลร้านสำหรับงานใหม่</Link></>}

      <h2 className="studio-section-title mt-6">ปรับกรอบวิดีโอ</h2>{!editable?<p className="mt-4 text-sm leading-7 text-muted">เลือกภาพกับคลิปและเตรียมกรอบก่อน หรือเปิดงานรอตรวจจากรายการด้านล่าง</p>:<div className="mt-5 space-y-4">
        <TextField label="ข้อความหัวโปรโมชั่น (ไม่จำเป็น)" value={plan.headline} maxLength={60} onChange={e=>edit({...plan,headline:e.target.value})}/>
        <TextField label="ข้อความชวนสั่งซื้อ (ไม่จำเป็น)" value={plan.cta} maxLength={60} onChange={e=>edit({...plan,cta:e.target.value})}/>
        <div className="frame-recent-list"><label className="text-sm">เริ่มคลิปที่วินาที<input className={selectClass} type="number" min={0} max={Math.max(0,(selectedClip?.metadata?.duration||0)-plan.duration)} step={0.1} value={plan.start} onChange={e=>edit({...plan,start:Number(e.target.value)})}/></label><label className="text-sm">ความยาว<select className={selectClass} value={plan.duration} onChange={e=>edit({...plan,duration:Number(e.target.value) as FramePlan['duration']})}>{[6,10,15].map(v=><option key={v} value={v}>{v} วินาที</option>)}</select></label></div>
        <label className="block text-sm">จัดคลิปในช่อง<select className={selectClass} value={plan.fit} onChange={e=>edit({...plan,fit:e.target.value as FramePlan['fit']})}><option value="contain">เห็นคลิปครบทั้งภาพ</option><option value="cover">เต็มช่อง (ครอบขอบภาพ)</option></select></label>
        <label className="flex gap-3 text-sm"><input type="checkbox" checked={plan.audio} onChange={e=>edit({...plan,audio:e.target.checked})}/>ใช้เสียงต้นฉบับ ถ้าคลิปมีเสียง</label>
        <details className="advanced-settings"><summary>ข้อมูลร้านในกรอบ · ตั้งค่าเพิ่มเติม</summary><div className="mt-4 space-y-4"><label className="flex gap-3 text-sm"><input type="checkbox" checked={plan.logo&&Boolean(detail.brand.logoId)} disabled={!detail.brand.logoId} onChange={e=>edit({...plan,logo:e.target.checked})}/>แสดงโลโก้ร้าน{!detail.brand.logoId?' (ยังไม่มีโลโก้)':''}</label>
        <label className="block text-sm">ช่องทางสั่งซื้อ<select className={selectClass} value={plan.contact} onChange={e=>edit({...plan,contact:e.target.value as FramePlan['contact']})}><option value="">ไม่แสดง</option>{(Object.keys(CONTACT_LABELS) as (keyof typeof CONTACT_LABELS)[]).filter(k=>detail.brand.contacts[k]).map(k=><option key={k} value={k}>{CONTACT_LABELS[k]}</option>)}</select></label>
        <label className="flex gap-3 text-sm"><input type="checkbox" disabled={!detail.brand.paymentMethods.length} checked={plan.payments} onChange={e=>edit({...plan,payments:e.target.checked})}/>แสดงช่องทางชำระเงินที่ร้านตั้งไว้</label>
        <label className="block text-sm">ข้อความที่ร้านยืนยัน<select className={selectClass} value={plan.trustIndex??''} onChange={e=>edit({...plan,trustIndex:e.target.value===''?null:Number(e.target.value)})}><option value="">ไม่แสดง</option>{detail.brand.claimsConfirmed&&detail.brand.trustStatements.map((text,i)=><option key={i} value={i}>{text}</option>)}</select></label>
        </div></details><Button variant="secondary" disabled={busy} onClick={()=>void act(async()=>{await renderPreview(detail.id,plan);})}>{preview?'อัปเดตตัวอย่างกรอบ':'สร้างตัวอย่างกรอบ'}</Button>
        <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" checked={confirmed} disabled={!previewCurrent} onChange={e=>setConfirmed(e.target.checked)}/>ตรวจภาพ ข้อความ ข้อมูลร้าน และช่วงคลิปแล้ว ยืนยันใช้โควตา 1 คลิป</label>
        <CreatorPrimaryAction quota={`เหลือ ${Math.max(0,studio.entitlement.limit-studio.entitlement.used-studio.entitlement.reserved)} คลิปเดือนนี้`}><Button className="w-full" disabled={busy||!confirmed||!previewCurrent||!studio.entitlement.enabled||!studio.storageAvailable} onClick={()=>void act(async()=>{await result(await fetch(`/api/frame/${detail.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:detail.revision,frame:plan,confirmed:true})}));setFeedback({tone:'success',message:'รับงานแล้ว กลับมาดาวน์โหลดวิดีโอได้เมื่อสร้างสำเร็จ'});})}>ยืนยันและสร้าง MP4</Button><p className="text-xs leading-6 text-muted">แนวตั้ง 720 × 1280 · จองพื้นที่สูงสุด 32 MB · ภาพโปรโมชั่นและราคาไม่ถูกเขียนใหม่</p></CreatorPrimaryAction>
      </div>}</CreatorSettingsPanel><CreatorCanvas title="ตัวอย่างกรอบวิดีโอ" busy={busy||Boolean(current&&['queued','running','retry'].includes(current.state))}>
        {current?.state==='succeeded'&&current.output_ready?<><video className="studio-video-result" controls playsInline src={`/api/assets/${current.output_asset_id}?inline=1`}/><CreatorResultActions downloadHref={`/api/assets/${current.output_asset_id}`} onNewVersion={()=>{setDetail(null);setPreview('');setPreviewKey('');setConfirmed(false);key.current=null;}}/><p className="canvas-caption">บันทึกในคลังให้อัตโนมัติแล้ว</p></>:<>        {preview&&<div className="mt-6"><div className="relative mx-auto aspect-[9/16] w-full max-w-80 overflow-hidden rounded-xl border border-white/10 bg-black"><video ref={video} src={`/api/assets/${clip}?inline=1`} controls playsInline muted={!plan.audio} preload="metadata" onLoadedMetadata={e=>{e.currentTarget.currentTime=plan.start;}} onTimeUpdate={e=>{if(e.currentTarget.currentTime>=plan.start+plan.duration){e.currentTarget.pause();e.currentTarget.currentTime=plan.start;}}} style={{position:'absolute',left:`${FRAME.clipX/720*100}%`,top:`${FRAME.clipY/1280*100}%`,width:`${FRAME.clipWidth/720*100}%`,height:`${FRAME.clipHeight/1280*100}%`,objectFit:plan.fit}}/><Image unoptimized fill src={preview} alt="ตัวอย่างกรอบโปรโมชั่นและข้อมูลร้าน" className="pointer-events-none"/></div><p className={`mt-3 text-xs leading-6 ${previewCurrent?'text-muted':'text-amber-200'}`}>{previewCurrent?'กรอบนี้ใช้ภาพเดียวกับที่จะส่งออก MP4 · ปุ่มเล่นไม่ปรากฏในไฟล์จริง':'มีการแก้ไข กรุณาอัปเดตตัวอย่างก่อนยืนยัน'}</p></div>}{!preview&&<CreatorGenerationState title="ภาพและคลิปของคุณในกรอบเดียว" description="เลือกไฟล์ทางซ้าย แล้วเตรียมกรอบจากข้อมูลร้าน"/>}{current&&current.state!=='review'&&<div className="canvas-state-banner" role="status">{MOTION_LABELS[current.state]}{current.state==='succeeded'&&!current.output_ready?' · ไฟล์หมดอายุหรือถูกลบแล้ว':''}</div>}</>}
      </CreatorCanvas></CreatorWorkspace>
      <section className="studio-recent"><h2 className="mb-5 text-xl font-bold">งานล่าสุด</h2>{!studio.jobs.length?<EmptyState title="ยังไม่มีงานจัดกรอบวิดีโอ" description="เตรียมภาพโปรโมชันและคลิปในคลังเพื่อเริ่มงาน" href="/dashboard/library" action="เปิดคลังไฟล์" />:<div className="frame-recent-list">{studio.jobs.map(job=><article key={job.id} className="min-w-0 rounded-2xl border border-white/10 p-5"><h3 className="break-words font-bold">{job.title}</h3><p className="mt-2 text-sm text-purple-200">{MOTION_LABELS[job.state]}</p><p className="mt-2 text-xs text-muted">{job.frame_plan.duration} วินาที · Brand Kit เวอร์ชัน {job.brand_version}</p>{job.state==='retry'&&<p className="mt-2 text-xs text-amber-200">เก็บกวาดไฟล์ก่อนลองใหม่ อาจใช้เวลาประมาณ 1 ชั่วโมงต่อรอบ</p>}<div className="mt-4 flex flex-wrap gap-4">{<Button variant="secondary" disabled={busy} onClick={()=>void act(()=>open(job.id))}>เปิดงาน</Button>}{job.state==='succeeded'&&(job.output_ready?<a href={`/api/assets/${job.output_asset_id}`} className="text-sm text-purple-200 underline">ดาวน์โหลด MP4</a>:<span className="text-xs text-muted">ไฟล์ถูกลบหรือหมดอายุแล้ว</span>)}{['review','queued','retry'].includes(job.state)&&<button disabled={busy} onClick={()=>{if(window.confirm('ยกเลิกงานนี้?'))void act(async()=>{await result(await fetch(`/api/frame/${job.id}`,{method:'DELETE'}));});}} className="text-xs text-muted underline">ยกเลิกงาน</button>}</div></article>)}</div>}</section>
    </>}
  </CreatorShell>;
}
